swagger: '2.0'
info:
  description: API per la gestione delle prenotazioni delle lezioni di guida
  version: 1.0.0
  title: Prenota e Guida
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
host: www.prenotaeguida.it
basePath: /api
tags:
  - name: authenticationToken
  - name: gestioneUtenti
  - name: disponibilit√†
schemes:
  - http
paths:
  /v1/authenticationToken:
    post:
      tags:
        - authenticationToken
      summary: Authentication method and token assignment
      operationId: authentication
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: user
          description: User that want to login
          required: true
          schema:
            $ref: '#/definitions/Credentials'
      responses:
        '200':
          description: user's credential readed in the correct way
        '401':
          description: no token provided
        '403':
          description: failed to authenticate token
  /v1/users:
    post:
      tags:
        - usersManagement
      summary: Creates a user
      consumes:
        - application/json
      parameters:
        - in: body
          name: user
          schema:
            $ref: '#/definitions/User'
          required: true
          description: User to create.
      responses:
        201:
          description: User created.
        400:
          description: Name, surname or user_type undefined.
    get:
      tags:
        - usersManagement
      summary: Gets all Users from the database
      produces: 
        - application/json
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/AllUsers'
        209:
          description: There are no Users.
  /v1/users/instructors:
    get:
      tags:
        - usersManagement
      summary: Gets all Instructors from the database
      produces: 
        - application/json
      responses:
        200:
          description: OK.
          schema:
            $ref: '#/definitions/AllInstructors'
        209:
          description: There are no Instructors.
  /v1/users/students:
    get:
      tags:
        - usersManagement
      summary: Gets all Students from the database
      produces: 
        - application/json
      responses:
        200:
          description: OK.
          schema:
            $ref: '#/definitions/AllStudents'
        209:
          description: There are no Students.
  /v1/users/{username}:
    get:
      tags:
        - usersManagement
      summary: Gets a user by Username
      produces: 
        - application/json
      parameters:
        - in: path
          name: username
          type: string
          required: true
          description: Alfanumeric ID of the user to get.
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/User'
        404:
          description: A User with the specified USERNAME was not found.
  /v1/users/{userID}:
    put:
      tags:
        - usersManagement
      summary: Updates a user by ID
      consumes:
        - application/json
      produces: 
        - application/json
      parameters:
        - in: path
          name: userID
          type: integer
          required: true
          description: Numeric ID of the user to get.
        - in: body
          name: userUpdateRequest
          description: User's data to be changed
          required: true
          schema:
            $ref: '#/definitions/UpdateUserRequest'
      responses:
        200:
          description: User updated
          schema:
            $ref: '#/definitions/User'
        210:
          description: User was not updated, name and surname were not changed
        400:
          description: Name, surname or user_type undefined
        404:
          description: A user with the specified ID was not found.
    delete:
      tags:
        - usersManagement
      summary: Deletes a user by ID
      produces: 
        - application/json
      parameters:
        - in: path
          name: userID
          type: integer
          required: true
          description: Numeric ID of the user to get.
      responses:
        200:
          description: User deleted
        404:
          description: A user with the specified ID was not found.
  /v2/availabilities:
    post:
      tags:
        - availabilities
      summary: Insert a new availabilities
      consumes: 
        - application/json
      parameters:
        - in: body
          name: availabilities
          schema: 
            $ref: '#/definitions/Availability'
          required: true
          description: Availabilities to insert 
      responses:
        201: 
          description: workshift created.
        412:
          description: Some required filed are emtpy or incorrect
        403: 
          description: The user isn't an instructor
        404: 
          description: The user doesn't exists
        476:
          description: The workshift overlaps another workshift
        409:
          description: Shift goes beyond working hours
    get:
      tags:
        - availabilities
      summary: Gets all availabilities of all instructors
      produces: 
        - application/json
      responses:
        200: 
          description: OK 
          schema: 
            $ref: '#/definitions/AllavailabilityAllInstructors'
        209: 
          description: There are not workshifts
  /v2/availabilities/{instructorID}:
    get:
      tags:
        - availabilities
      summary: Gets all availabilities by id of instructor
      produces: 
        - application/json
      parameters: 
        - in: path
          name: instructorID 
          type: string
          required: true
          description: Alfanumeric ID of the instructor
      responses:
        200: 
          description: OK 
          schema: 
            $ref: '#/definitions/Allavailability'
        209: 
          description: There are not workshifts
  /v2/availabilities/{availabilityID}:
    put:  
      tags:
        - availabilities
      summary: Update an avaliability by its id 
      consumes:
        - application/json
      produces: 
        - application/json
      parameters: 
        - in: path
          name: availabilityID 
          type: integer
          required: true
          description: Alfanumeric ID of the avaliability to change
        - in: body
          name: availabilitiesUpdateRequest
          description: Avaliability's data to be changed
          required: true
          schema: 
            $ref: '#/definitions/AvailabilitiesUpdateRequest'
      responses:
        200: 
          description: OK 
          schema: 
            $ref: '#/definitions/Availability' 
        404:
          description: The user does not exist
        400:
          description: The workshift doesn't exists
        403:  
          description: The user isn't an instructor
        409:
          description: Shift goes beyond working hours
        412: 
          description: Some required filed are emtpy or incorrect
        476:
          description: The workshift overlaps another workshif
    delete:
      tags:
        - availabilities
      summary: Deletes a avaliability by id 
      produces: 
         - application/json
      parameters:
         - in: path
           name: availabilityID
           type: integer
           required: true
           description: Alfanumeric ID of the avaliability to delete
      responses:
        200:
          description: Cancellation done
        404:
          description: The user does not exist
        403:  
          description: The user isn't an instructor
  /v2/reservations/{studentID}:
    post:
      tags:
        - reservations
      summary: Insert a new reservation
      consumes: 
        - application/json
      parameters:
        - in: path
          name: studentID
          type: string
          required: true
          description: Alfanumeric ID of the user that did the request
        - in: body
          name: reservations
          schema: 
            $ref: '#/definitions/Reservation'
          required: true
          description: Reservation to insert 
      responses:
        201: 
          description: reservation created.
        403: 
          description: The user in params isn't a student
        404: 
          description: The user doesn't exist
        481:
          description: The slotID does not exist in availabilities
        491:
          description: Reservation already made
    get:  
      tags:
        - reservations
      summary: Gets all student reservations and all time slots available
      produces: 
        - application/json
      parameters:
        - in: path
          name: studentID
          type: string
          required: true
          description: Alfanumeric ID of the user that did the request
      responses:
        200: 
          description: OK 
          schema: 
            $ref: '#/definitions/AllReservations'
        209:
          description: There aren't reservation of this student
        403:  
          description: The user in params isn't a student
        404:
          description: The user does not exist
  /v2/reservations/{reservationID}:
    delete:
      tags:
        - reservations
      summary: Deletes a reservation by it's id 
      produces: 
         - application/json
      parameters:
         - in: path
           name: reservationID
           type: integer
           required: true
           description: Alfanumeric ID of the reservation to delete
      responses:
        200:
          description: Cancellation done
        400:
          description: The reservation does not exist
    #-----------------------DEFINITION#-----------------------
definitions:
  Reservation:
    type: object
    properties:
      instructor:
        type: string
      student:
        type: string
      time_slot:
        type: object
        properties:
          date: 
            type: object
            properties:
              day: 
                type: integer
              month:
                type: integer
              year:
                type: integer
          start_time:
            type: object
            properties:
              hour:
                type: integer
              minute:
                type: integer
    example:
      - instructor: 
          {
            value: '291234'
          }
        student: 
          {
            value: '146892'
          }
        start_time:
          {
            data: 
              {
                day: 6,
                month: 12,
                year: 2011
              },
            start_time: 
              {
                hour: 15,
                minute: 30
              }
          }
    xml:
      name: Reservation
  AllReservations:
    type: object
    properties:
      Reservation:
        type: array
        items:
          type: object
          properties:
            instructor:
              type: string
            student:
              type: string
            time_slot:
              type: object
              properties:
                date: 
                  type: object
                  properties:
                    day: 
                      type: integer
                    month:
                      type: integer
                    year:
                      type: integer
                start_time:
                  type: object
                  properties:
                    hour:
                      type: integer
                    minute:
                      type: integer
      FreeReservation:
        type: array
        items:
          type: object
          properties:
            id: 
              type: string
            time:
              type: object
              properties:
                hour:
                  type: integer
                minute:
                  type: integer
            date: 
              type: object
              properties:
                day: 
                  type: integer
                month:
                  type: integer
                year:
                  type: integer
            instructor:
              type: string
            student:
              type: string
    example:
      - Reservation:
          [
            {
              instructor: 
                {
                  value: '291234'
                },
              student: 
                {
                  value: '146892'
                },
              time_slot:
                {
                  date: 
                    {
                      day: 6,
                      month: 12,
                      year: 2011
                    },
                  start_time: 
                    {
                      hour: 15,
                      minute: 30
                    }
                }
            },
            {
              instructor: 
                {
                  value: '291234'
                },
              student: 
                {
                  value: '146892'
                },
              time_slot:
                {
                  date: 
                    {
                      day: 6,
                      month: 12,
                      year: 2011
                    },
                  start_time: 
                    {
                      hour: 15,
                      minute: 30
                    }
                }
            }
          ]
        FreeReservation:
          [
            {
              id: 
                {
                  value: '291234'
                },
              time:
                {
                  hour: 15,
                  minute: 30
                },
              date: 
                {
                  day: 6,
                  month: 12,
                  year: 2011
                },
              instructor:
                {
                  value: '1489y31'
                },
              student:
                {
                  value: 'null'
                }
            },
            {
              id: 
                {
                  value: '291234'
                },
              time:
                {
                  hour: 15,
                  minute: 30
                },
              date: 
                {
                  day: 6,
                  month: 12,
                  year: 2011
                },
              instructor:
                {
                  value: '1489y31'
                },
              student:
                {
                  value: 'null'
                }
            },
            {
              id: 
                {
                  value: '291234'
                },
              time:
                {
                  hour: 15,
                  minute: 30
                },
              date: 
                {
                  day: 6,
                  month: 12,
                  year: 2011
                },
              instructor:
                {
                  value: '1489y31'
                },
              student:
                {
                  value: 'null'
                }
            },
          ]
    xml:
      name: AllReservations
  Availability:
    type: object
    properties: 
      data: 
        type: object
        properties:
          day: 
            type: integer
          month:
            type: integer
          year:
            type: integer
      instructor:
        type: string
      start_time:
        type: object
        properties:
          hour:
            type: integer
          minute:
            type: integer
      end_time: 
        type: object
        properties:
          hour:
            type: integer
          minute:
            type: integer
      duration:
        type: integer
      time_slot:
        type: array
        items:
          type: object
          properties:
            hour:
              type: integer
            minute:
              type: integer
    example:
      - data: 
          {
            day: 6,
            month: 12,
            year: 2011
          }
        instructor: 
          {
            value: '291234'
          }
        start_time: 
          {
            hour: 15,
            minute: 30
          }
        end_time:
          {
            hour: 16,
            minute: 30
          }
        duration: 
          {
            value: 30
          }
        time_slot:
          [
            {
              hour: 15,
              minute: 30
            },
            {
              hour: 16,
              minute: 00
            }
          ]
    xml:
      name: Availability  
  Allavailability:
    type: array
    items:
      type: object
      properties: 
        data: 
          type: object
          properties:
            day: 
              type: integer
            month:
              type: integer
            year:
              type: integer
        instructor:
          type: string
        start_time:
          type: object
          properties:
            hour:
              type: integer
            minute:
              type: integer
        end_time: 
          type: object
          properties:
            hour:
              type: integer
            minute:
              type: integer
        duration:
          type: integer
        time_slot:
          type: array
          items:
            type: object
            properties:
              hour:
                type: integer
              minute:
                type: integer
    example:
      - data: 
          {
            day: 6,
            month: 12,
            year: 2011
          }
        instructor: 
          {
            value: '291234'
          }
        start_time: 
          {
            hour: 15,
            minute: 30
          }
        end_time:
          {
            hour: 16,
            minute: 30
          }
        duration: 
          {
            value: 30
          }
        time_slot:
          [
            {
              hour: 15,
              minute: 30
            },
            {
              hour: 16,
              minute: 00
            }
          ]
      - data: 
          {
            day: 7,
            month: 12,
            year: 2011
          }
        instructor: 
          {
            value: '291234'
          }
        start_time: 
          {
            hour: 14,
            minute: 30
          }
        end_time:
          {
            hour: 17,
            minute: 30
          }
        duration: 
          {
            value: 30
          }
        time_slot:
          [
            {
              hour: 14,
              minute: 30
            },
            {
              hour: 15,
              minute: 00
            },
            {
              hour: 15,
              minute: 30
            },
            {
              hour: 16,
              minute: 00
            },
            {
              hour: 16,
              minute: 30
            },
            {
              hour: 17,
              minute: 00
            }
          ]
    xml:
      name: Allavailability 
  AllavailabilityAllInstructors:
    type: array
    items:
      type: object
      properties: 
        data: 
          type: object
          properties:
            day: 
              type: integer
            month:
              type: integer
            year:
              type: integer
        instructor:
          type: string
        start_time:
          type: object
          properties:
            hour:
              type: integer
            minute:
              type: integer
        end_time: 
          type: object
          properties:
            hour:
              type: integer
            minute:
              type: integer
        duration:
          type: integer
        time_slot:
          type: array
          items:
            type: object
            properties:
              hour:
                type: integer
              minute:
                type: integer
    example:
      - data: 
          {
            day: 6,
            month: 12,
            year: 2011
          }
        instructor: 
          {
            value: '291234'
          }
        start_time: 
          {
            hour: 15,
            minute: 30
          }
        end_time:
          {
            hour: 16,
            minute: 30
          }
        duration: 
          {
            value: 30
          }
        time_slot:
          [
            {
              hour: 15,
              minute: 30
            },
            {
              hour: 16,
              minute: 00
            }
          ]
      - data: 
          {
            day: 7,
            month: 12,
            year: 2011
          }
        instructor: 
          {
            value: '291234'
          }
        start_time: 
          {
            hour: 14,
            minute: 30
          }
        end_time:
          {
            hour: 17,
            minute: 30
          }
        duration: 
          {
            value: 30
          }
        time_slot:
          [
            {
              hour: 14,
              minute: 30
            },
            {
              hour: 15,
              minute: 00
            },
            {
              hour: 15,
              minute: 30
            },
            {
              hour: 16,
              minute: 00
            },
            {
              hour: 16,
              minute: 30
            },
            {
              hour: 17,
              minute: 00
            }
          ]
      - data: 
          {
            day: 7,
            month: 12,
            year: 2011
          }
        instructor: 
          {
            value: '301234'
          }
        start_time: 
          {
            hour: 14,
            minute: 30
          }
        end_time:
          {
            hour: 17,
            minute: 30
          }
        duration: 
          {
            value: 30
          }
        time_slot:
          [
            {
              hour: 14,
              minute: 30
            },
            {
              hour: 15,
              minute: 00
            },
            {
              hour: 15,
              minute: 30
            },
            {
              hour: 16,
              minute: 00
            },
            {
              hour: 16,
              minute: 30
            },
            {
              hour: 17,
              minute: 00
            }
          ]
    xml:
      name: AllavailabilityAllInstructors
  AvailabilitiesUpdateRequest:
    type: object
    properties: 
      data: 
        type: object
        properties:
          day: 
            type: integer
          month:
            type: integer
          year:
            type: integer
      instructor:
        type: string
      start_time:
        type: object
        properties:
          hour:
            type: integer
          minute:
            type: integer
      end_time: 
        type: object
        properties:
          hour:
            type: integer
          minute:
            type: integer
      duration:
        type: integer
      time_slot:
        type: array
        items:
          type: object
          properties:
            hour:
              type: integer
            minute:
              type: integer
    example:
      - data: 
          {
            day: 6,
            month: 12,
            year: 2011
          }
        instructor: 
          {
            value: '291234'
          }
        start_time: 
          {
            hour: 15,
            minute: 30
          }
        end_time:
          {
            hour: 16,
            minute: 30
          }
        duration: 
          {
            value: 30
          }
        time_slot:
          [
            {
              hour: 15,
              minute: 30
            },
            {
              hour: 16,
              minute: 00
            }
          ]
    xml:
      name: AvailabilitiesUpdateRequest
  Credentials:
    type: object
    properties:
      username:
        type: string
      password:
        type: string
    xml:
      name: Credentials
  User:
    type: object
    properties:
      username:
        type: string
      password:
        type: string
      user_type:
        type: string
      name:
        type: string
      surname:
        type: string
      photo:
        type: string
    example:
      - username: MarioRossi0
        password: j8sd3
        user_type: Studente
        name: Mario
        surname: Rossi
        photo: ---
    xml:
      name: User
  AllUsers:
    type: array
    items:
      $ref: '#/definitions/User'
    example:
      - username: MarioRossi0
        password: j8sd3
        user_type: Studente
        name: Mario
        surname: Rossi
        photo: ---
      - username: MarioRossi1
        password: nvm13
        user_type: Studente
        name: Mario
        surname: Rossi
        photo: ---
      - username: CarloCracco0
        password: s621h
        user_type: Istruttore
        name: Carlo
        surname: Cracco
        photo: ---
    xml:
      name: ArrayOfUsers
  AllStudents:
    type: array
    items:
      $ref: '#/definitions/User'
    example:
      - username: MarioRossi0
        password: j8sd3
        user_type: Studente
        name: Mario
        surname: Rossi
        photo: ---
      - username: MarioRossi1
        password: nvm13
        user_type: Studente
        name: Mario
        surname: Rossi
        photo: ---
      - username: CarloCracco0
        password: s621h
        user_type: Studente
        name: Carlo
        surname: Cracco
        photo: ---
    xml:
      name: ArrayOfStudents
  AllInstructors:
    type: array
    items:
      $ref: '#/definitions/User'
    example:
      - username: MarioRossi0
        password: j8sd3
        user_type: Istruttore
        name: Mario
        surname: Rossi
        photo: ---
      - username: MarioRossi1
        password: nvm13
        user_type: Istruttore
        name: Mario
        surname: Rossi
        photo: ---
      - username: CarloCracco0
        password: s621h
        user_type: Istruttore
        name: Carlo
        surname: Cracco
        photo: ---
    xml:
      name: ArrayOfInstructors  
  UpdateUserRequest:
    type: object
    properties:
      user_type:
        type: string
      name:
        type: string
      surname:
        type: string
      photo:
        type: string
      changePsw:
        type: boolean
    xml:
      name: UpdateUserRequest
  